name: staging

on:
  push:
    branches: staging

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Login
      run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: docker build --build-arg URL=$URL -t ghcr.io/${{ secrets.OWNER }}/ilmotunkki-cms:latest-staging .
    - name: Push
      run: docker push ghcr.io/${{ secrets.OWNER }}/ilmotunkki-cms:latest-staging
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}" > ~/.ssh/deploy.key
          chmod 600 ~/.ssh/deploy.key
          cat >>~/.ssh/config<<END
          Host production
            HostName ${{ secrets.SSH_HOST }}
            User ${{ secrets.SSH_USER }}
            IdentityFile ~/.ssh/deploy.key
            StrictHostKeyChecking no
          END
      - name: pull
        run: ssh production 'cd ./staging && docker-compose pull cms'
      - name: restart
        run: ssh production 'cd ./staging && docker-compose up -d --force-recreate --no-deps cms'

